#!/usr/bin/env node
/**
 * Generate `dev/cordis.xiaobo.local.yml`, a dsh patch overlay that mounts the
 * built persona plugin by absolute path.
 *
 * Absolute paths cannot be committed, so the overlay is generated per machine.
 * The package path form (`dsh plugin add`) exists for anything longer-lived.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pluginEntry = resolve(repoRoot, 'packages/xiaobo-persona/lib/index.js').replaceAll('\\', '/')
const outputFile = resolve(repoRoot, 'dev/cordis.xiaobo.local.yml')

const patch = [
  '# GENERATED by scripts/dev-patch.mjs — do not edit, do not commit.',
  '# Mounts the built Xiaobo persona plugin by absolute path.',
  '- insert:',
  '    - id: xiaobo-persona',
  `      name: '${pluginEntry}'`,
  '',
].join('\n')

mkdirSync(dirname(outputFile), { recursive: true })
writeFileSync(outputFile, patch, 'utf8')

console.log(`wrote ${outputFile}`)
console.log('boot a harness source checkout with:')
console.log(`  pnpm dsh web --patch ${outputFile}`)
